version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: semantic-release
    versions:
    - 17.4.0
    - 17.4.1
  - dependency-name: tape
    versions:
    - 5.1.1
    - 5.2.1
  - dependency-name: mime
    versions:
    - 2.5.0
