language: node_js

node_js:
  - "5"
  - "4"

env:
  - EXIST_DB_VERSION=eXist-3.0.RC1 JAVA_HOME=/usr/lib/jvm/java-8-oracle

addons:
  apt:
    packages:
      - oracle-java8-installer

install:
  - wget https://github.com/eXist-db/exist/archive/$EXIST_DB_VERSION.tar.gz -O /tmp/$EXIST_DB_VERSION.tar.gz
  - tar -xvf /tmp/$EXIST_DB_VERSION.tar.gz
  - cd exist-$EXIST_DB_VERSION
  - ./build.sh
  - nohup sh bin/startup.sh &
  - cd ..
  - npm install -q
