language: node_js

node_js:
  - "5"
  - "4"

env:
  - EXIST_DB_VERSION=eXist-3.1.1
  - EXIST_DB_VERSION=eXist-3.0
  - EXIST_DB_VERSION=eXist-2.2

addons:
  apt:
    packages:
      - oracle-java8-installer

sudo: false

notifications:
  email: false

before_install:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - export EXIST_DB_FOLDER=${HOME}/exist/${EXIST_DB_VERSION}
  - ci/setup-db.sh
  - npm prune

install:
  - npm install -q

before_script:
  - ci/start-db.sh
  - curl -Lo travis_after_all.py https://git.io/vLSON

script:
  - npm test

after_success:
  - python travis_after_all.py
  - npm run semantic-release

after_script:
  - cd ${EXIST_DB_FOLDER}
  - bin/shutdown.sh

before_cache:
  - ci/teardown-db.sh

cache:
  directories:
    - node_modules
    - ${HOME}/exist
