language: node_js

node_js:
  - "10"
  - "8"
  - "6"

env:
  - EXIST_DB_VERSION=eXist-5.0.0-RC1
  - EXIST_DB_VERSION=eXist-4.2.1
  - EXIST_DB_VERSION=eXist-3.6.1
  - EXIST_DB_VERSION=eXist-2.2

addons:
  apt:
    packages:
      - oracle-java8-installer

sudo: false

notifications:
  email: false

before_install:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - export EXIST_DB_FOLDER=${HOME}/exist/${EXIST_DB_VERSION}
  - ci/setup-db.sh
  - npm prune

install:
  - npm install -q

before_script:
  - ci/start-db.sh

script:
  - npm test

after_success:
  - npm install -g travis-deploy-once
  - travis-deploy-once "npm run semantic-release"

after_script:
  - cd ${EXIST_DB_FOLDER}
  - bin/shutdown.sh

before_cache:
  - ci/teardown-db.sh

# cache:
#   directories:
#     - ~/.npm
#     - node_modules
#     - ${HOME}/exist
