language: node_js

node_js:
  - "5"
  - "4"

env:
  - EXIST_DB_VERSION=eXist-3.0.RC1 JAVA_HOME=/usr/lib/jvm/java-8-oracle

addons:
  apt:
    packages:
      - oracle-java8-installer

install:
  - ci/setup.sh
  - npm install -q

before_script:
  - nohup ${HOME}/exist-${EXIST_DB_VERSION}/bin/startup.sh &
  - sleep 15
  - cat nohup.out
  - curl http://127.0.0.1:8080/

script:
  - npm test

after_script:
  - $HOME/exist-${EXIST_DB_VERSION}/bin/shutdown.sh

cache:
  directories:
  - $HOME/exist-${EXIST_DB_VERSION}
