language: node_js

node_js:
  - "5"
  - "4"

env:
  - EXIST_DB_VERSION=eXist-3.0.RC1 JAVA_HOME=/usr/lib/jvm/java-8-oracle

addons:
  apt:
    packages:
      - oracle-java8-installer

install:
  - ci/setup.sh
  - npm install -q

before_script:
  - ci/exist-${EXIST_DB_VERSION}/bin/startup.sh

script:
  - npm test

after_script:
  - ci/exist-${EXIST_DB_VERSION}/bin/shutdown.sh