#!/usr/bin/env node

const {connect} = require('../../index')

// read connection options from ENV
const connectionOptions = require('../connection')

async function ls (connectionOptions, collection) {
    try {
        const db = connect(connectionOptions)
        const query = `
        declare variable $collection external;

        (
            xmldb:get-child-collections($collection),
            xmldb:get-child-resources($collection)
        )
            => (function ($collections) { array { $collections } })()
            => serialize(map { "method": "json" })
        `
        const result = await db.queries.readAll(query, { variables: {collection} })
        const json = JSON.parse(result.pages.toString())
        console.log(json)
    }
    catch (e) {
        let message = e.faultString ? e.faultString : e.message
        console.error("Could not run query! Reason:", message)
        process.exit(1)
    }
}

if (!process.argv[2]) {
    console.log("Usage: exist-ls [collection]")
    console.log("Example: exist-ls /db/apps")
    process.exit(9)
}

const dbPath = process.argv[2] 

// run query
ls(connectionOptions, dbPath)
