#!/usr/bin/env node

const {connect} = require('../../index')
const {readFileSync} = require("fs")

// read connection options from ENV
const connectionOptions = require('../connection')

if (!process.argv[3]) {
  console.log("Usage: exist-upload [local file] [remote file]")
  console.log("Example: exist-upload ./test.xml /db/test.xml")
  process.exit(9)
}

// read parameters
const localFilePath = process.argv[2]
const remoteFilePath = process.argv[3]

;(async function () {
  try {
    process.stdout.write(`Upload ${localFilePath} to ${remoteFilePath}\n`)
    const db = connect(connectionOptions)
    const fileContents = readFileSync(localFilePath);
    process.stdout.write("uploading...")
    process.stdout.clearLine()
    process.stdout.cursorTo(0)

    process.stdout.write("parsing...")
    const fileHandle = await db.documents.upload(fileContents)
    await db.documents.parseLocal(fileHandle, remoteFilePath, {})
    process.stdout.clearLine()
    process.stdout.cursorTo(0)
    console.log("uploaded to", server, "✔︎")
    process.exit(0)
  }
  catch (e) { 
    let message = e.faultString ? e.faultString : e.message
    console.error(message)
    process.exit(1)
  }
})()
